name: Publish Protobuf to BSR
description: 'Publish Protobuf Definitions to Buf Schema Registry'

inputs:
  planton_cloud_service_cli_env:
    description: 'name of the planton cloud cli environment live or test'
    required: false
    default: 'live'
  planton_cloud_service_client_id:
    description: 'client-id of the planton cloud machine account to be used for generated api token for making api requests to planton cloud service.'
    required: true
  planton_cloud_service_client_secret:
    description: 'client-secret of the planton cloud machine account to be used for generated api token for making api requests to planton cloud service.'
    required: true
  planton_cloud_artifact_store_id:
    description: 'id of the artifact-store on planton-cloud'
    required: true
  release_version:
    description: 'semantic version of the protobufs to be used for the release'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.planton_cloud_service_cli_env }}
    - ${{ inputs.planton_cloud_service_client_id }}
    - ${{ inputs.planton_cloud_service_client_secret }}
    - ${{ inputs.planton_cloud_artifact_store_id }}
    - ${{ inputs.release_version }}
